# docker-compose.yml
version: '3.8'
services:
  db:
    image: mysql:8.0 # 使用官方 MySQL 8.0 镜像
    container_name: mysql_ecom_qa
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Bs@1107849531' # !!!重要: 换成你自己的复杂密码!!!
      MYSQL_DATABASE: 'ecom_qa_db' # 数据库名字，可以不改
      MYSQL_USER: 'ecom_user' # 用户名，可以不改
      MYSQL_PASSWORD: 'Bs@1107849531' # !!!重要: 换成你自己的用户密码!!!
    ports:
      # 将容器的 3306 端口映射到你电脑的 3307 端口
      - "3307:3306"
    volumes:
      # 让数据保存在你电脑上，这样容器重启数据不丢失
      - mysql_data:/var/lib/mysql
    networks:
      - ecom_network

volumes:
  mysql_data:

networks:
  ecom_network:
    driver: bridge